# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: includes/burgerbot_common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fincludes/burgerbot_common.proto\x12\x1f\x64\x65vices.protos.burgerbot.common\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"W\n\x0cOrderCommand\x12\x13\n\x02id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00\x12\x17\n\x04\x63ode\x18\x02 \x01(\tB\t\xfa\x42\x06r\x04\x10\x00\x18\x32\x12\x19\n\x05level\x18\x03 \x01(\x02\x42\n\xfa\x42\x07\n\x05-\x00\x00\x00\x00\">\n\x12OrderResultCommand\x12\x13\n\x02id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00\x12\x13\n\x0bis_disabled\x18\x02 \x01(\x08\x42!Z\x1f\x64\x65vices/protos/burgerbot/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'includes.burgerbot_common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037devices/protos/burgerbot/common'
  _globals['_ORDERCOMMAND'].fields_by_name['id']._options = None
  _globals['_ORDERCOMMAND'].fields_by_name['id']._serialized_options = b'\372B\0042\002 \000'
  _globals['_ORDERCOMMAND'].fields_by_name['code']._options = None
  _globals['_ORDERCOMMAND'].fields_by_name['code']._serialized_options = b'\372B\006r\004\020\000\0302'
  _globals['_ORDERCOMMAND'].fields_by_name['level']._options = None
  _globals['_ORDERCOMMAND'].fields_by_name['level']._serialized_options = b'\372B\007\n\005-\000\000\000\000'
  _globals['_ORDERRESULTCOMMAND'].fields_by_name['id']._options = None
  _globals['_ORDERRESULTCOMMAND'].fields_by_name['id']._serialized_options = b'\372B\0042\002 \000'
  _globals['_ORDERCOMMAND']._serialized_start=126
  _globals['_ORDERCOMMAND']._serialized_end=213
  _globals['_ORDERRESULTCOMMAND']._serialized_start=215
  _globals['_ORDERRESULTCOMMAND']._serialized_end=277
# @@protoc_insertion_point(module_scope)
