# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services.burgerbot import connector_pb2 as services_dot_burgerbot_dot_connector__pb2


class ConnectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOrder = channel.unary_unary(
                '/devices.protos.burgerbot.ConnectorService/GetOrder',
                request_serializer=services_dot_burgerbot_dot_connector__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=services_dot_burgerbot_dot_connector__pb2.GetOrderResponse.FromString,
                )
        self.CompleteOrder = channel.unary_unary(
                '/devices.protos.burgerbot.ConnectorService/CompleteOrder',
                request_serializer=services_dot_burgerbot_dot_connector__pb2.CompleteOrderRequest.SerializeToString,
                response_deserializer=services_dot_burgerbot_dot_connector__pb2.CompleteOrderResponse.FromString,
                )
        self.MarkFailedOrder = channel.unary_unary(
                '/devices.protos.burgerbot.ConnectorService/MarkFailedOrder',
                request_serializer=services_dot_burgerbot_dot_connector__pb2.MarkFailedOrderRequest.SerializeToString,
                response_deserializer=services_dot_burgerbot_dot_connector__pb2.MarkFailedOrderResponse.FromString,
                )


class ConnectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkFailedOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=services_dot_burgerbot_dot_connector__pb2.GetOrderRequest.FromString,
                    response_serializer=services_dot_burgerbot_dot_connector__pb2.GetOrderResponse.SerializeToString,
            ),
            'CompleteOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteOrder,
                    request_deserializer=services_dot_burgerbot_dot_connector__pb2.CompleteOrderRequest.FromString,
                    response_serializer=services_dot_burgerbot_dot_connector__pb2.CompleteOrderResponse.SerializeToString,
            ),
            'MarkFailedOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkFailedOrder,
                    request_deserializer=services_dot_burgerbot_dot_connector__pb2.MarkFailedOrderRequest.FromString,
                    response_serializer=services_dot_burgerbot_dot_connector__pb2.MarkFailedOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'devices.protos.burgerbot.ConnectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConnectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/devices.protos.burgerbot.ConnectorService/GetOrder',
            services_dot_burgerbot_dot_connector__pb2.GetOrderRequest.SerializeToString,
            services_dot_burgerbot_dot_connector__pb2.GetOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompleteOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/devices.protos.burgerbot.ConnectorService/CompleteOrder',
            services_dot_burgerbot_dot_connector__pb2.CompleteOrderRequest.SerializeToString,
            services_dot_burgerbot_dot_connector__pb2.CompleteOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MarkFailedOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/devices.protos.burgerbot.ConnectorService/MarkFailedOrder',
            services_dot_burgerbot_dot_connector__pb2.MarkFailedOrderRequest.SerializeToString,
            services_dot_burgerbot_dot_connector__pb2.MarkFailedOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
