# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/burgerbot/connector.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from includes import burgerbot_common_pb2 as includes_dot_burgerbot__common__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"services/burgerbot/connector.proto\x12\x18\x64\x65vices.protos.burgerbot\x1a\x1fincludes/burgerbot_common.proto\x1a\x17validate/validate.proto\"/\n\x0fGetOrderRequest\x12\x1c\n\x0btray_number\x18\x01 \x01(\rB\x07\xfa\x42\x04*\x02 \x00\"\x8d\x01\n\x10GetOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x04\x12\x11\n\tclient_id\x18\x02 \x01(\x04\x12\x13\n\x0btray_number\x18\x03 \x01(\r\x12?\n\x08\x63ommands\x18\x04 \x03(\x0b\x32-.devices.protos.burgerbot.common.OrderCommand\"M\n\x14\x43ompleteOrderRequest\x12\x19\n\x08order_id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00\x12\x1a\n\tclient_id\x18\x02 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00\"\x17\n\x15\x43ompleteOrderResponse\"\xee\x01\n\x16MarkFailedOrderRequest\x12\x19\n\x08order_id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00\x12\x1a\n\tclient_id\x18\x02 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00\x12O\n\x12\x63ompleted_commands\x18\x03 \x03(\x0b\x32\x33.devices.protos.burgerbot.common.OrderResultCommand\x12L\n\x0f\x66\x61iled_commands\x18\x04 \x03(\x0b\x32\x33.devices.protos.burgerbot.common.OrderResultCommand\"\x19\n\x17MarkFailedOrderResponse2\xe5\x02\n\x10\x43onnectorService\x12\x63\n\x08GetOrder\x12).devices.protos.burgerbot.GetOrderRequest\x1a*.devices.protos.burgerbot.GetOrderResponse\"\x00\x12r\n\rCompleteOrder\x12..devices.protos.burgerbot.CompleteOrderRequest\x1a/.devices.protos.burgerbot.CompleteOrderResponse\"\x00\x12x\n\x0fMarkFailedOrder\x12\x30.devices.protos.burgerbot.MarkFailedOrderRequest\x1a\x31.devices.protos.burgerbot.MarkFailedOrderResponse\"\x00\x42\x1aZ\x18\x64\x65vices/protos/burgerbotb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.burgerbot.connector_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030devices/protos/burgerbot'
  _globals['_GETORDERREQUEST'].fields_by_name['tray_number']._options = None
  _globals['_GETORDERREQUEST'].fields_by_name['tray_number']._serialized_options = b'\372B\004*\002 \000'
  _globals['_COMPLETEORDERREQUEST'].fields_by_name['order_id']._options = None
  _globals['_COMPLETEORDERREQUEST'].fields_by_name['order_id']._serialized_options = b'\372B\0042\002 \000'
  _globals['_COMPLETEORDERREQUEST'].fields_by_name['client_id']._options = None
  _globals['_COMPLETEORDERREQUEST'].fields_by_name['client_id']._serialized_options = b'\372B\0042\002 \000'
  _globals['_MARKFAILEDORDERREQUEST'].fields_by_name['order_id']._options = None
  _globals['_MARKFAILEDORDERREQUEST'].fields_by_name['order_id']._serialized_options = b'\372B\0042\002 \000'
  _globals['_MARKFAILEDORDERREQUEST'].fields_by_name['client_id']._options = None
  _globals['_MARKFAILEDORDERREQUEST'].fields_by_name['client_id']._serialized_options = b'\372B\0042\002 \000'
  _globals['_GETORDERREQUEST']._serialized_start=122
  _globals['_GETORDERREQUEST']._serialized_end=169
  _globals['_GETORDERRESPONSE']._serialized_start=172
  _globals['_GETORDERRESPONSE']._serialized_end=313
  _globals['_COMPLETEORDERREQUEST']._serialized_start=315
  _globals['_COMPLETEORDERREQUEST']._serialized_end=392
  _globals['_COMPLETEORDERRESPONSE']._serialized_start=394
  _globals['_COMPLETEORDERRESPONSE']._serialized_end=417
  _globals['_MARKFAILEDORDERREQUEST']._serialized_start=420
  _globals['_MARKFAILEDORDERREQUEST']._serialized_end=658
  _globals['_MARKFAILEDORDERRESPONSE']._serialized_start=660
  _globals['_MARKFAILEDORDERRESPONSE']._serialized_end=685
  _globals['_CONNECTORSERVICE']._serialized_start=688
  _globals['_CONNECTORSERVICE']._serialized_end=1045
# @@protoc_insertion_point(module_scope)
